name: Award Submission Preparation
on:
  schedule:
    - cron: '0 8 * * 1'  # Every Monday at 8 AM
  workflow_dispatch:

jobs:
  prepare-award-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Generate award submission package
        run: |
          python -c "
          from awards.final_submission_package import AwardSubmissionPackage
          package = AwardSubmissionPackage()
          submission = package.generate_submission_package()
          readiness = package.validate_readiness()
          print('Award Submission Package Generated!')
          print(f'Overall Readiness: {readiness[\"overall_readiness\"]}')
          print(f'Average Score: {readiness[\"average_confidence_score\"]:.2f}')
          "
          
      - name: Upload award package
        uses: actions/upload-artifact@v3
        with:
          name: award-submission-package
          path: award_submission_package.json
          
  update-analytics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Generate analytics dashboard
        run: |
          python -c "
          from src.interfaces.analytics_dashboard import AnalyticsDashboard
          dashboard = AnalyticsDashboard()
          report = dashboard.export_dashboard_report()
          print('Analytics Dashboard Updated!')
          "
          
      - name: Generate ML training report
        run: |
          python -c "
          from src.core.ml_training_pipeline import MLTrainingPipeline
          pipeline = MLTrainingPipeline()
          report = pipeline.generate_ml_report()
          print('ML Training Report Generated!')
          "
