name: Daily Evolution Analysis
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  analyze-and-evolve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests beautifulsoup4
        
      - name: Run evolution analysis
        run: python src/core/evolution_engine.py
        
      - name: Generate evolution report
        run: |
          python -c "
          from src.core.evolution_engine import EvolutionEngine
          engine = EvolutionEngine()
          report = engine.generate_evolution_report()
          with open('evolution-report.md', 'w') as f:
              f.write(report)
          "
