name: Production Deployment
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        run: |
          python -c "
          from src.core.evo_assistant import EvoCodeAssistant
          from src.core.evolution_engine import EvolutionEngine
          print('Core modules imported successfully')
          "
          
      - name: Validate AI models
        run: python -c "from src.core.advanced_ai import AdvancedAIIntegration; print('Advanced AI models validated')"
        
      - name: Check code quality
        run: |
          python -m py_compile src/core/*.py
          echo "Code compilation successful"
          
  deploy-docs:
    needs: test-and-validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: \${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          
  publish-release:
    needs: test-and-validate
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create release artifacts
        run: |
          mkdir -p release
          cp -r src/ release/
          cp requirements.txt release/
          cp README.md release/
          zip -r evocode-ai-\${{ github.ref_name }}.zip release/
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: \${{ github.event.release.upload_url }}
          asset_path: ./evocode-ai-\${{ github.ref_name }}.zip
          asset_name: evocode-ai-\${{ github.ref_name }}.zip
          asset_content_type: application/zip
